<template>
  <section class="py-24 h-full grow flex items-center">
    <div class="container mx-auto flex justify-center px-4">
      <article class="md:w-3/4 lg:w-2/3 p-8 border rounded-md bg-gray-200 shadow-lg">
        <h1 class="mb-8 text-3xl font-black">Terms and Conditions</h1>
        <p class="mb-8">
          The Acapunks is decentralized software running on the
          <a href="https://acala.network" target="_blank" rel="noopener noreferrer">Acala Network</a>.
          This website is only an interface built to help users interact with
          that Acala smart contract. No Acapunk ownership is managed by this
          website or by
          <a href="https://twitter.com/parachainlabs" target="_blank" rel="noopener noreferrer">Parachain Labs</a>.
          Users are entirely responsible for the
          safety and management of their own private Acala wallets and
          validating all transactions generated by Parachain Labs before
          approving them. Use of this website is at the user's own risk and
          Parachain Labs is not liable for any incorrect or failed transactions.
          Furthermore, as the contract runs on Acala, Parachain Labs has no
          power to undo, reverse, or restore any transactions.
        </p>
        <p class="mb-8">
          In order to use this website, and any related tools it may provide,
          you agree to hold Parachain Labs harmless for any and all problems,
          errors, and failures, no matter the cause or source of those errors,
          and accept sole responsibility for all transactions.
        </p>
        <p>AcaPunks and Parachain Labs are not affiliated with the CryptoPunks or Larva Labs.</p>
      </article>
    </div>
  </section>
</template>
